---
version: '3'
services:

    build:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - type: volume
            source: webapps
            target: /build/webapps
        secrets:
          - db_root_password
          
    tomcat:
        image: andreptb/tomcat:6.0.53-jdk6
        restart: on-failure
        ports:
          - "8080:8080"
          - "3306:3306"
          - "33060:33060"
        volumes:
          - type: volume
            source: webapps
            target: /usr/local/tomcat/webapps

    mysql:
        image: mysql:8-debian
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
          - "33060:33060"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app42paas
        volumes:
          - type: volume
            source: mysql
            target: /var/lib/mysql
        secrets:
          - db_root_password

volumes:
    webapps:
    mysql:

secrets:
    db_root_password:
        file: ./db_root_password.txt