---
services:

    build:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - type: volume
            source: src
            target: /src
        secrets:
          - db_root_password


    tomcat:
        image: tomcat:8-alpine
        depends_on:
          - build
        restart: on-failure
        ports:
          - "8080:8080"
        volumes:
          - type: volume
            source: src
            target: /src

          
    mysql:
        image: mysql:8-debian
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
          - "33060:33060"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app42paas
        volumes:
          - type: volume
            source: mysql
            target: /var/lib/mysql
        secrets:
          - db_root_password

volumes:
    src:
    mysql:

secrets:
    db_root_password:
        file: ./db_root_password.txt