---
version: '3'
services:

    tomcat:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          DB_USERNAME: shephertz
          DB_PASSWORD: secret
          DB_IP: mysql
          DB_NAME: app42paas
        restart: on-failure
        ports:
          - "8080:8080"
          
    mysql:
        image: mysql:5.7-debian
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
          - "33060:33060"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootsecret
            MYSQL_DATABASE: app42paas
            MYSQL_USER: shephertz
            MYSQL_PASSWORD: secret
        volumes:
          - type: volume
            source: mysql
            target: /var/lib/mysql

volumes:
    mysql: